### ISSUE TITLE
How to train in tensorflow 1.1

### ISSUE THREAD

**Issue by sounansu** [drakelevy/FSRCNN-TensorFlow#3]
Hi.
I tried to train by 
'Train main.py'

An error occured.

```
OSError: [Errno 2] No such file or directory: 'FastTrain'
```

I changed directory name  'Train' to 'FastTrain'. (Is it correct?)
And, I tried  again!

```
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    tf.app.run()
  File "/home/sounansu/anaconda3/envs/fsrcnn/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 42, in main
    fsrcnn.run()
  File "/home/sounansu/anaconda3/FSRCNN-TensorFlow/model.py", line 107, in run
    self.run_train()
  File "/home/sounansu/anaconda3/FSRCNN-TensorFlow/model.py", line 115, in run_train
    train_input_setup(self)
  File "/home/sounansu/anaconda3/FSRCNN-TensorFlow/utils.py", line 217, in train_input_setup
    input_, label_ = preprocess(data[i], scale)
  File "/home/sounansu/anaconda3/FSRCNN-TensorFlow/utils.py", line 49, in preprocess
    image.close()
  File "/home/sounansu/anaconda3/envs/fsrcnn/lib/python2.7/site-packages/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: close
```

What happen to me?

**Comment by sounansu** [comment]
I solved this problem.
Old pillow have bug at close operation.

https://bitbucket.org/blockdiag/blockdiag/issues/63/attributeerror-close

I updated pillow version 2.5.1.
And, 'Train main.py' again.

```
Beginning training setup...
Training setup took 0.96350312233 seconds with 1 threads
Total setup time took 1.02058911324 seconds with 1 threads
Training...
Epoch: [ 1], step: [10], time: [2.0913], loss: [9.62728882]

Epoch: [10], step: [2030], time: [29.3310], loss: [4.06100845]
Start Average: [10.693321], End Average: [10.261442], Improved: [4.04%]
```

Thank you.
